# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BSBTDflXDGSSCnktU31UYYTmMmOByfPB
"""

grid = [
    ['00', '01', '02'],
    ['10', '11', '12'],
    ['20', '21', '22']
]

visited = [[False] * 3 for _ in range(3)]

directions = [
    (0, 1),    # Right
    (1, 0),    # Down
    (0, -1),   # Left
    (-1, 0)    # Up
]


def find_paths(row, col, destination, path, cost):

    # Destination reached
    if grid[row][col] == destination:
        print("Path:", " -> ".join(path))
        print("Cost:", cost)
        print()
        return

    visited[row][col] = True

    for dr, dc in directions:

        new_row = row + dr
        new_col = col + dc

        if (0 <= new_row < 3 and
                0 <= new_col < 3 and
                not visited[new_row][new_col]):

            find_paths(
                new_row,
                new_col,
                destination,
                path + [grid[new_row][new_col]],
                cost + 1
            )

    # Backtracking
    visited[row][col] = False


# User input
source = input("Enter source: ")
destination = input("Enter destination: ")

# Find source coordinates
start_row = -1
start_col = -1

for i in range(3):
    for j in range(3):
        if grid[i][j] == source:
            start_row = i
            start_col = j

# Check whether source exists
if start_row == -1:
    print("Source not found.")
else:
    find_paths(
        start_row,
        start_col,
        destination,
        [source],
        0
    )

"""grid = [
    ['00', '01', '02'],
    ['10', '11', '12'],
    ['20', '21', '22']
]

visited = [[False] * 3 for _ in range(3)]

directions = [
    (0, 1),    # Right
    (1, 0),    # Down
    (0, -1),   # Left
    (-1, 0)    # Up
]

min_cost = float('inf')
max_cost = float('-inf')

min_path = []
max_path = []


def find_paths(row, col, destination, path, cost):

    global min_cost, max_cost, min_path, max_path

    # Destination reached
    if grid[row][col] == destination:

        # Show ALL paths and costs
        print("Path:", " -> ".join(path))
        print("Cost:", cost)
        print()

        # Find minimum
        if cost < min_cost:
            min_cost = cost
            min_path = path.copy()

        # Find maximum
        if cost > max_cost:
            max_cost = cost
            max_path = path.copy()

        return

    visited[row][col] = True

    for dr, dc in directions:

        new_row = row + dr
        new_col = col + dc

        if (0 <= new_row < 3 and
                0 <= new_col < 3 and
                not visited[new_row][new_col]):

            find_paths(
                new_row,
                new_col,
                destination,
                path + [grid[new_row][new_col]],
                cost + 1
            )

    # Backtracking
    visited[row][col] = False


# User input
source = input("Enter source: ")
destination = input("Enter destination: ")

# Find source coordinates
start_row = -1
start_col = -1

for i in range(3):
    for j in range(3):
        if grid[i][j] == source:
            start_row = i
            start_col = j

# Check source
if start_row == -1:
    print("Source not found.")

else:

    # Find all paths
    find_paths(
        start_row,
        start_col,
        destination,
        [source],
        0
    )

    # Show minimum and maximum
    if min_cost == float('inf'):

        print("Destination not found.")

    else:

        print("========== MINIMUM ==========")
        print("Path:", " -> ".join(min_path))
        print("Cost:", min_cost)

        print()

        print("========== MAXIMUM ==========")
        print("Path:", " -> ".join(max_path))
        print("Cost:", max_cost)
"""

grid = [
    ['00', '01', '02'],
    ['10', '11', '12'],
    ['20', '21', '22']
]

visited = [[False] * 3 for _ in range(3)]

directions = [
    (0, 1),    # Right
    (1, 0),    # Down
    (0, -1),   # Left
    (-1, 0)    # Up
]

min_cost = float('inf')
max_cost = float('-inf')

min_path = []
max_path = []


def find_paths(row, col, destination, path, cost):

    global min_cost, max_cost, min_path, max_path

    # Destination reached
    if grid[row][col] == destination:

        # Show ALL paths and costs
        print("Path:", " -> ".join(path))
        print("Cost:", cost)
        print()

        # Find minimum
        if cost < min_cost:
            min_cost = cost
            min_path = path.copy()

        # Find maximum
        if cost > max_cost:
            max_cost = cost
            max_path = path.copy()

        return

    visited[row][col] = True

    for dr, dc in directions:

        new_row = row + dr
        new_col = col + dc

        if (0 <= new_row < 3 and
                0 <= new_col < 3 and
                not visited[new_row][new_col]):

            find_paths(
                new_row,
                new_col,
                destination,
                path + [grid[new_row][new_col]],
                cost + 1
            )

    # Backtracking
    visited[row][col] = False


# User input
source = input("Enter source: ")
destination = input("Enter destination: ")

# Find source coordinates
start_row = -1
start_col = -1

for i in range(3):
    for j in range(3):
        if grid[i][j] == source:
            start_row = i
            start_col = j

# Check source
if start_row == -1:
    print("Source not found.")

else:

    # Find all paths
    find_paths(
        start_row,
        start_col,
        destination,
        [source],
        0
    )

    # Show minimum and maximum
    if min_cost == float('inf'):

        print("Destination not found.")

    else:

        print("========== MINIMUM ==========")
        print("Path:", " -> ".join(min_path))
        print("Cost:", min_cost)

        print()

        print("========== MAXIMUM ==========")
        print("Path:", " -> ".join(max_path))
        print("Cost:", max_cost)

grid = [
    ['00', '01', '02'],
    ['10', '11', '12'],
    ['20', '21', '22']
]

visited = [[False] * 3 for _ in range(3)]

directions = [
    (0, 1),    # Right
    (1, 0),    # Down
    (0, -1),   # Left
    (-1, 0)    # Up
]

min_cost = float('inf')
max_cost = float('-inf')

min_path = []
max_path = []

path_count = 0


def find_paths(row, col, destination, path, cost):

    global min_cost, max_cost, min_path, max_path, path_count

    # Destination reached
    if grid[row][col] == destination:

        # Count the path
        path_count += 1

        # Display every path and its cost
        print("Path:", " -> ".join(path))
        print("Cost:", cost)
        print()

        # Minimum cost
        if cost < min_cost:
            min_cost = cost
            min_path = path.copy()

        # Maximum cost
        if cost > max_cost:
            max_cost = cost
            max_path = path.copy()

        return

    visited[row][col] = True

    for dr, dc in directions:

        new_row = row + dr
        new_col = col + dc

        if (0 <= new_row < 3 and
                0 <= new_col < 3 and
                not visited[new_row][new_col]):

            find_paths(
                new_row,
                new_col,
                destination,
                path + [grid[new_row][new_col]],
                cost + 1
            )

    # Backtracking
    visited[row][col] = False


# User input
source = input("Enter source: ")
destination = input("Enter destination: ")

# Find source coordinates
start_row = -1
start_col = -1

for i in range(3):
    for j in range(3):
        if grid[i][j] == source:
            start_row = i
            start_col = j

# Check source
if start_row == -1:
    print("Source not found.")

else:

    find_paths(
        start_row,
        start_col,
        destination,
        [source],
        0
    )

    if path_count == 0:

        print("Destination not found.")

    else:

        print("================================")
        print("Number of possible paths:", path_count)

        print()
        print("========== MINIMUM ==========")
        print("Path:", " -> ".join(min_path))
        print("Cost:", min_cost)

        print()
        print("========== MAXIMUM ==========")
        print("Path:", " -> ".join(max_path))
        print("Cost:", max_cost)